service: rbac-dev-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}
  stackName: rbac-dev-dynamodb

resources:
  Resources:
    RBACDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rbac-dev
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE

  Outputs:
    TableName:
      Value: !Ref RBACDynamoTable
      Export:
        Name: rbac-dev-dynamodb-TableName
    TableArn:
      Value: !GetAtt RBACDynamoTable.Arn
      Export:
        Name: rbac-dev-dynamodb-TableArn
